### PR TITLE
New e2e_test_data

### PR DESCRIPTION
**Pull request by AgaFra**
I created bigger test database, it works with the visible_data as it is, but unfortunately it doesn't work for me when I want to display "operator", maybe do to null.

### CODE REVIEW

**Comment by raven-wing** [comment]
Pull request should not be opne for not working code.
'unfortunately it doesn't work for me when I want to display "operator", maybe do to null' automatically says this should not be delivered here.

If its due to some bug -> report issue.

**Comment by raven-wing** [comment]
To tell the truth... Why so much data? It will slow tests down yet do not provide much usecases.

**Comment by AgaFra** [comment]
> Pull request should not be opne for not working code. 'unfortunately it doesn't work for me when I want to display "operator", maybe do to null' automatically says this should not be delivered here.
> 
> If its due to some bug -> report issue.

The code works and the issue is reported as well.

**Comment by AgaFra** [comment]
> To tell the truth... Why so much data? It will slow tests down yet do not provide much usecases.

I thought that we can have also load tests. If you have another idea how to test this, feel free to limit data to the smaller size.

**Comment by AgaFra** [comment]
Accidentally closed

**Review by raven-wing — APPROVED** [review]

**Comment by raven-wing** [comment]
Due to problems with this data license closing pull request. 
Please reopen when issue will be resolved

**Pull request closed without merging**
